import type {
  Complaint,
  Notification,
  Provider,
  Review,
  ServiceCategory,
  ServiceRequest,
} from "./types";

export const categories: ServiceCategory[] = [
  {
    slug: "maids",
    name: "Maids & Domestic Help",
    icon: "home",
    description: "Trusted maids and domestic helpers for daily household support.",
    group: "Domestic",
  },
  {
    slug: "cleaning",
    name: "Cleaning Services",
    icon: "sparkle",
    description: "Deep cleaning, regular upkeep, and move-in/move-out cleaning.",
    group: "Domestic",
  },
  {
    slug: "cooks",
    name: "Cooks",
    icon: "chef",
    description: "Home cooks for daily meals, meal prep, and special occasions.",
    group: "Domestic",
  },
  {
    slug: "plumbers",
    name: "Plumbing",
    icon: "wrench",
    description: "Leaks, blockages, installations, and full plumbing repairs.",
    group: "Maintenance",
  },
  {
    slug: "electricians",
    name: "Electrical",
    icon: "bolt",
    description: "Wiring, fixtures, load issues, and certified electrical work.",
    group: "Maintenance",
  },
  {
    slug: "carpenters",
    name: "Carpentry",
    icon: "hammer",
    description: "Furniture repair, custom woodwork, doors, and fittings.",
    group: "Maintenance",
  },
  {
    slug: "painters",
    name: "Painting",
    icon: "roller",
    description: "Interior and exterior painting with clean, careful finishing.",
    group: "Maintenance",
  },
  {
    slug: "ac-technicians",
    name: "AC & Cooling",
    icon: "snowflake",
    description: "AC installation, servicing, gas refills, and repair.",
    group: "Technical",
  },
  {
    slug: "appliance-repair",
    name: "Appliance Repair",
    icon: "washer",
    description: "Fridge, washing machine, oven, and appliance repairs.",
    group: "Technical",
  },
  {
    slug: "gardeners",
    name: "Gardening & Landscaping",
    icon: "leaf",
    description: "Garden upkeep, lawn care, planting, and landscaping.",
    group: "Outdoor",
  },
  {
    slug: "handymen",
    name: "Handyman",
    icon: "tools",
    description: "Small fixes, furniture assembly, and general odd jobs.",
    group: "Maintenance",
  },
];

export const providers: Provider[] = [
  {
    id: "ahmed-khan",
    name: "Ahmed Khan",
    category: "Plumbing",
    categorySlug: "plumbers",
    title: "Plumber",
    experienceYears: 7,
    rating: 4.8,
    reviewCount: 132,
    jobsCompleted: 640,
    availability: "Available",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 2", "Precinct 5", "Precinct 9"],
    verification: "Verified",
    skills: ["Leak repair", "Pipe installation", "Bathroom fittings"],
    servicesOffered: ["Sink & tap repair", "Leak detection", "Geyser installation"],
    bio: "Seven years fixing plumbing across Bahria Town. Known for showing up on time and leaving the site clean.",
    registeredDate: "Mar 2023",
    languages: ["Urdu", "English"],
    responseRate: 98,
  },
  {
    id: "muhammad-ali",
    name: "Muhammad Ali",
    category: "Plumbing",
    categorySlug: "plumbers",
    title: "Plumber",
    experienceYears: 5,
    rating: 4.5,
    reviewCount: 74,
    jobsCompleted: 318,
    availability: "Busy",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 1", "Precinct 4"],
    verification: "Verified",
    skills: ["Drainage", "Water tanks", "Emergency callouts"],
    servicesOffered: ["Blockage clearing", "Pump repair", "Tank cleaning"],
    bio: "Reliable plumber specialising in drainage and water-tank work for homes and small businesses.",
    registeredDate: "Aug 2023",
    languages: ["Urdu"],
    responseRate: 92,
  },
  {
    id: "bilal-ahmed",
    name: "Bilal Ahmed",
    category: "Electrical",
    categorySlug: "electricians",
    title: "Electrician",
    experienceYears: 9,
    rating: 4.9,
    reviewCount: 201,
    jobsCompleted: 890,
    availability: "Available",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 2", "Precinct 6", "Precinct 11"],
    verification: "Verified",
    skills: ["Wiring", "Panel upgrades", "Lighting design"],
    servicesOffered: ["Fault finding", "Fixture installation", "Inverter setup"],
    bio: "Certified electrician with nine years of residential and commercial wiring experience.",
    registeredDate: "Jan 2023",
    languages: ["Urdu", "English"],
    responseRate: 97,
  },
  {
    id: "sara-mehmood",
    name: "Sara Mehmood",
    category: "Maids & Domestic Help",
    categorySlug: "maids",
    title: "Domestic Helper",
    experienceYears: 6,
    rating: 4.7,
    reviewCount: 98,
    jobsCompleted: 520,
    availability: "Available",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 7", "Precinct 8"],
    verification: "Verified",
    skills: ["Housekeeping", "Laundry", "Kitchen help"],
    servicesOffered: ["Daily cleaning", "Deep cleaning", "Meal assistance"],
    bio: "Dependable and discreet domestic helper, trusted by families across the community.",
    registeredDate: "Feb 2023",
    languages: ["Urdu"],
    responseRate: 96,
  },
  {
    id: "usman-raza",
    name: "Usman Raza",
    category: "AC & Cooling",
    categorySlug: "ac-technicians",
    title: "AC Technician",
    experienceYears: 8,
    rating: 4.6,
    reviewCount: 116,
    jobsCompleted: 455,
    availability: "Available",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 3", "Precinct 10"],
    verification: "Verified",
    skills: ["AC servicing", "Gas refill", "Installation"],
    servicesOffered: ["Split AC service", "Gas top-up", "New installation"],
    bio: "AC specialist for split and inverter units — servicing, gas refills, and clean installations.",
    registeredDate: "Apr 2023",
    languages: ["Urdu", "English"],
    responseRate: 94,
  },
  {
    id: "kiran-abbas",
    name: "Kiran Abbas",
    category: "Cleaning Services",
    categorySlug: "cleaning",
    title: "Cleaner",
    experienceYears: 4,
    rating: 4.4,
    reviewCount: 52,
    jobsCompleted: 240,
    availability: "Off Duty",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 5"],
    verification: "Verified",
    skills: ["Deep cleaning", "Move-out cleaning", "Sofa shampooing"],
    servicesOffered: ["Home deep clean", "Sofa & carpet cleaning"],
    bio: "Thorough cleaner for full-home deep cleans, move-out cleans, and upholstery care.",
    registeredDate: "Sep 2023",
    languages: ["Urdu"],
    responseRate: 90,
  },
  {
    id: "imran-sheikh",
    name: "Imran Sheikh",
    category: "Carpentry",
    categorySlug: "carpenters",
    title: "Carpenter",
    experienceYears: 11,
    rating: 4.8,
    reviewCount: 143,
    jobsCompleted: 610,
    availability: "Available",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 2", "Precinct 9", "Precinct 12"],
    verification: "Verified",
    skills: ["Furniture repair", "Custom cabinets", "Door installation"],
    servicesOffered: ["Furniture assembly", "Custom shelving", "Door fitting"],
    bio: "Master carpenter for bespoke woodwork, repairs, and fittings across the community.",
    registeredDate: "Dec 2022",
    languages: ["Urdu"],
    responseRate: 95,
  },
  {
    id: "farhan-qureshi",
    name: "Farhan Qureshi",
    category: "Gardening & Landscaping",
    categorySlug: "gardeners",
    title: "Gardener",
    experienceYears: 5,
    rating: 4.5,
    reviewCount: 39,
    jobsCompleted: 180,
    availability: "Available",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 6", "Precinct 7"],
    verification: "Verified",
    skills: ["Lawn care", "Planting", "Pruning"],
    servicesOffered: ["Garden upkeep", "Lawn maintenance", "Seasonal planting"],
    bio: "Keeps gardens tidy and healthy — lawn care, planting, and pruning done properly.",
    registeredDate: "Jun 2023",
    languages: ["Urdu"],
    responseRate: 91,
  },
  {
    id: "nadia-hassan",
    name: "Nadia Hassan",
    category: "Maids & Domestic Help",
    categorySlug: "maids",
    title: "Domestic Helper",
    experienceYears: 3,
    rating: 4.3,
    reviewCount: 27,
    jobsCompleted: 96,
    availability: "Away",
    serviceArea: "Bahria Town Karachi",
    precincts: ["Precinct 8"],
    verification: "Pending Verification",
    skills: ["Housekeeping", "Light cooking"],
    servicesOffered: ["Daily cleaning"],
    bio: "New to the platform and currently completing her management verification.",
    registeredDate: "Jan 2026",
    languages: ["Urdu"],
    responseRate: 85,
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    providerId: "ahmed-khan",
    author: "Zahra M.",
    rating: 5,
    date: "14 Aug 2026",
    text: "Arrived on time and fixed the leaking kitchen sink quickly. Clean work and fair pricing.",
    verifiedResident: true,
  },
  {
    id: "r2",
    providerId: "ahmed-khan",
    author: "Bilal S.",
    rating: 5,
    date: "02 Aug 2026",
    text: "Very professional. Explained the problem before starting and left everything spotless.",
    verifiedResident: true,
  },
  {
    id: "r3",
    providerId: "ahmed-khan",
    author: "Fatima R.",
    rating: 4,
    date: "21 Jul 2026",
    text: "Good work overall. Slightly late but kept me informed on the way.",
    verifiedResident: true,
  },
  {
    id: "r4",
    providerId: "bilal-ahmed",
    author: "Omar K.",
    rating: 5,
    date: "18 Aug 2026",
    text: "Solved an electrical fault two other electricians couldn't. Highly recommend.",
    verifiedResident: true,
  },
  {
    id: "r5",
    providerId: "bilal-ahmed",
    author: "Ayesha T.",
    rating: 5,
    date: "05 Aug 2026",
    text: "Neat wiring, professional attitude, and completed the inverter setup the same day.",
    verifiedResident: true,
  },
  {
    id: "r6",
    providerId: "sara-mehmood",
    author: "Hamza N.",
    rating: 5,
    date: "11 Aug 2026",
    text: "Sara has been helping our family for months now. Trustworthy and hardworking.",
    verifiedResident: true,
  },
];

export const requests: ServiceRequest[] = [
  {
    id: "10234",
    providerId: "ahmed-khan",
    providerName: "Ahmed Khan",
    service: "Plumbing",
    categorySlug: "plumbers",
    status: "Accepted",
    date: "16 Aug 2026",
    time: "4:00 PM",
    description: "The kitchen sink is leaking. Need assistance today between 4–6 PM.",
    resident: "Zahra M.",
    precinct: "Precinct 9",
  },
  {
    id: "10235",
    providerId: "bilal-ahmed",
    providerName: "Bilal Ahmed",
    service: "Electrical",
    categorySlug: "electricians",
    status: "Pending",
    date: "17 Aug 2026",
    time: "11:00 AM",
    description: "Ceiling fan replacement in two bedrooms plus a flickering light.",
    resident: "Omar K.",
    precinct: "Precinct 6",
  },
  {
    id: "10236",
    providerId: "usman-raza",
    providerName: "Usman Raza",
    service: "AC & Cooling",
    categorySlug: "ac-technicians",
    status: "Completed",
    date: "15 Aug 2026",
    time: "2:00 PM",
    description: "Annual AC servicing for two split units in the lounge.",
    resident: "Fatima R.",
    precinct: "Precinct 3",
  },
  {
    id: "10237",
    providerId: "sara-mehmood",
    providerName: "Sara Mehmood",
    service: "Maids & Domestic Help",
    categorySlug: "maids",
    status: "Scheduled",
    date: "18 Aug 2026",
    time: "9:00 AM",
    description: "Weekly house cleaning for a 3-bedroom home.",
    resident: "Hamza N.",
    precinct: "Precinct 7",
  },
  {
    id: "10238",
    providerId: "imran-sheikh",
    providerName: "Imran Sheikh",
    service: "Carpentry",
    categorySlug: "carpenters",
    status: "Cancelled",
    date: "14 Aug 2026",
    time: "12:00 PM",
    description: "Fix a broken wardrobe door hinge.",
    resident: "Ayesha T.",
    precinct: "Precinct 2",
  },
];

export const complaints: Complaint[] = [
  {
    id: "C-201",
    providerId: "muhammad-ali",
    providerName: "Muhammad Ali",
    reason: "No-show",
    details: "Provider did not arrive for a scheduled callout and did not respond.",
    reportedBy: "Resident, Precinct 1",
    date: "12 Aug 2026",
    status: "Under Review",
  },
  {
    id: "C-202",
    providerId: "kiran-abbas",
    providerName: "Kiran Abbas",
    reason: "Poor service",
    details: "Cleaning was incomplete and items were left out of place.",
    reportedBy: "Resident, Precinct 5",
    date: "09 Aug 2026",
    status: "Open",
  },
  {
    id: "C-203",
    providerId: "farhan-qureshi",
    providerName: "Farhan Qureshi",
    reason: "Incorrect service",
    details: "Booked pruning but only basic lawn mowing was completed.",
    reportedBy: "Resident, Precinct 6",
    date: "30 Jul 2026",
    status: "Resolved",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    title: "Request accepted",
    detail: "Ahmed Khan (Verified Plumber) accepted your request — arriving 4:00 PM.",
    time: "10 min ago",
    kind: "success",
    unread: true,
  },
  {
    id: "n2",
    title: "Appointment confirmed",
    detail: "Sara Mehmood is scheduled for 9:00 AM tomorrow.",
    time: "2 hours ago",
    kind: "info",
    unread: true,
  },
  {
    id: "n3",
    title: "Review reminder",
    detail: "How was Usman Raza's AC service? Leave a review to help your neighbours.",
    time: "1 day ago",
    kind: "warning",
  },
];

export const favorites: Provider[] = [
  providers[0], // Ahmed
  providers[3], // Sara
  providers[4], // Usman
];

export function getProvider(id: string): Provider | undefined {
  return providers.find((p) => p.id === id);
}

export function getProvidersByCategory(slug: string): Provider[] {
  return providers.filter((p) => p.categorySlug === slug);
}

export function getCategory(slug: string): ServiceCategory | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getReviewsForProvider(providerId: string): Review[] {
  return reviews.filter((r) => r.providerId === providerId);
}

export function getProviderByCategorySlug(slug: string): Provider | undefined {
  return providers.find((p) => p.categorySlug === slug);
}

export const categoryGroups = [
  "Domestic",
  "Maintenance",
  "Technical",
  "Outdoor",
] as const;
